#--------------------->Queries<-------------------#
query GetUserNotification($getNotificationsUserId: ID!) {
  GetNotifications(userId: $getNotificationsUserId) {
    _id
    ReceiverId
    isGroup
    isSeen
    NotiReference
    SenderInfo {
      _id
      Firstname
      Lastname
      Image
    }
    NotiEngine {
      GroupName
      NotiImage
      NotiText
    }
  }
}

#--------------------->Mutations<-----------------#
mutation SendNotification($notiData: NotiData!) {
  SendNotification(NotiData: $notiData) {
    message
    success
  }
}

mutation DeleteNotification($notiId: ID!, $deleteNotificationUserId: ID!) {
  DeleteNotification(NotiId: $notiId, userId: $deleteNotificationUserId) {
    message
    success
  }
}

 mutation Viewed_Notifications($notiId: [ID]) {
   ViewedNotifications(NotiId: $notiId) {
     message
     success
   }
 }
